### ISSUE TITLE
Plugin can't be installed using BRAT, raising main.js missing error

### ISSUE THREAD

**Issue by hxhc** [aidenlx/obsidian-zotero-plugin#1]
![image](https://user-images.githubusercontent.com/13412966/155873384-f5b888ba-5836-4c70-b68d-d33ea69a3fd5.png)

**Comment by aidenlx** [comment]
Sorry, forgot to update installation guide, this plugin has not been published yet because the support for node module in web worker is not yet available in obsidian

**Comment by danieltomasz** [comment]
sorry for offtopic, but @hxhc, what theme you were using on the screenshot?

**Comment by hxhc** [comment]
> sorry for offtopic, but @hxhc, what theme you were using on the screenshot?

It is [blue topaz](https://forum.obsidian.md/t/theme-blue-topaz/6425?msclkid=8364c217ce8311ec8bec53a052917a99), and the font is Bookerly.
